-- Seed control_ensayos_catalogo with new tests (Fixed columns)
INSERT INTO control_ensayos_catalogo (codigo, nombre, area, orden, activo, created_at) VALUES
-- SUELO
('su-proc-mod', 'PROC MOD', 'SUELO', 1, true, NOW()),
('su-sales', 'SALES SU', 'SUELO', 2, true, NOW()),
('su-clorur', 'CLORUR SU', 'SUELO', 3, true, NOW()),
('su-sulfa', 'SULFA SU', 'SUELO', 4, true, NOW()),
('su-ph', 'PH', 'SUELO', 5, true, NOW()),
('su-corte', 'CORTE', 'SUELO', 6, true, NOW()),
('su-cbr', 'CBR', 'SUELO', 7, true, NOW()),
('su-grav-solido', 'GRAV SOLIDO', 'SUELO', 8, true, NOW()),
('su-comp-no-conf', 'COMPRESION NO CONFINADA', 'SUELO', 9, true, NOW()),
('su-corr-proctor', 'CORRECCION PROCTOR', 'SUELO', 10, true, NOW()),
('su-mat-organica', 'CONTENIDO MAT. ORGANICA', 'SUELO', 11, true, NOW()),
('su-dpl', 'DPL', 'SUELO', 12, true, NOW()),
('su-gran-macro', 'GRAN. MACRO', 'SUELO', 13, true, NOW()),
('su-placa-carga', 'PLACA CARGA', 'SUELO', 14, true, NOW()),
('su-triaxial', 'TRIAXIAL', 'SUELO', 15, true, NOW()),
('su-hinchamiento', 'HINCHAMIENTO', 'SUELO', 16, true, NOW()),
('su-colapso', 'COLAPSO', 'SUELO', 17, true, NOW()),
('su-permeabilidad', 'PERMEABILIDAD', 'SUELO', 18, true, NOW()),
('su-termica', 'TERMICA', 'SUELO', 19, true, NOW()),
('su-hidrometro', 'ANÁLISIS GRAN.(HIDRÓMETRO)', 'SUELO', 20, true, NOW()),

-- AGREGADO
('ag-malla-200', 'MALLA 200', 'AGREGADO', 1, true, NOW()),
('ag-ge-fino', 'G.E. FINO', 'AGREGADO', 2, true, NOW()),
('ag-pus-puc', 'PUS PUC', 'AGREGADO', 3, true, NOW()),
('ag-gra-ag', 'GRA AG', 'AGREGADO', 4, true, NOW()),
('ag-c-hume-ag', 'C HUME AG', 'AGREGADO', 5, true, NOW()),
('ag-eq-arena', 'EQ ARENA', 'AGREGADO', 6, true, NOW()),
('ag-pe-ge-grav', 'PE GRAV GE GRAV', 'AGREGADO', 7, true, NOW()),
('ag-carga-puntual', 'CARGA PUNTUAL', 'AGREGADO', 8, true, NOW()),
('ag-pe-ge-roca', 'PE ROCA GE ROCA', 'AGREGADO', 9, true, NOW()),
('ag-densidad-roca', 'DENSIDAD ROCA', 'AGREGADO', 10, true, NOW()),
('ag-abra-menor', 'ABRASION MENOR (C131)', 'AGREGADO', 11, true, NOW()),
('ag-abra-mayor', 'ABRASION MAYOR', 'AGREGADO', 12, true, NOW()),
('ag-sulf-magnesio', 'INAL AGRE/SULF MAGNESIO (AG08)', 'AGREGADO', 13, true, NOW()),
('ag-alcalisis', 'ALCALISIS', 'AGREGADO', 14, true, NOW()),
('ag-chatas-planas', 'CHATAS PLANAS ALARGADAS', 'AGREGADO', 15, true, NOW()),
('ag-caras-fract', 'CARAS FRACTURADAS', 'AGREGADO', 16, true, NOW()),
('ag-incide-durab', 'INDICE DURABILIDAD', 'AGREGADO', 17, true, NOW()),
('ag-sales-mtc', 'SALES SOLUBLES MTC', 'AGREGADO', 18, true, NOW()),
('ag-cloruros', 'CLORUROS', 'AGREGADO', 19, true, NOW()),
('ag-sulfatos', 'SULFATOS', 'AGREGADO', 20, true, NOW()),
('ag-terrones', 'TERRONES ARCILLA', 'AGREGADO', 21, true, NOW()),
('ag-azul-metileno', 'AZUL METILENO', 'AGREGADO', 22, true, NOW()),
('ag-part-livianas', 'PARTICULAS LIVIANAS', 'AGREGADO', 23, true, NOW()),
('ag-imp-organicas', 'IMPUREZAS ORGANICAS', 'AGREGADO', 24, true, NOW()),
('ag-max-min', 'MAXIMO MINIMO', 'AGREGADO', 25, true, NOW()),
('ag-angularidad', 'ANGULARIDAD', 'AGREGADO', 26, true, NOW()),
('ag-adherencia', 'ADHERENCIA GRUESO', 'AGREGADO', 27, true, NOW()),
('ag-solido-agua', 'SOLIDO EN AGUA', 'AGREGADO', 28, true, NOW()),
('ag-riedel-weber', 'RIEDEL WEBER', 'AGREGADO', 29, true, NOW()),
('ag-react-alcalis', 'REACTIVIDAD ALCALIS', 'AGREGADO', 30, true, NOW()),

-- HUMEDAD SUELO
('hs-humedad', 'CONTENIDO DE HUMEDAD', 'HUMEDAD SUELO', 1, true, NOW()),

-- DENSIDAD SUELO
('ds-densidad', 'DENSIDAD EN CAMPO', 'DENSIDAD SUELO', 1, true, NOW()),

-- CONCRETO
('co-fresco', 'CONTROL DE CALIDAD C. FRESCO', 'CONCRETO', 1, true, NOW()),
('co-diamantina', 'DIAMANTINA', 'CONCRETO', 2, true, NOW()),
('co-cubitos', 'CUBITOS CONCRETO', 'CONCRETO', 3, true, NOW()),
('co-carbonatacion', 'CARBONATACION', 'CONCRETO', 4, true, NOW()),
('co-dis-mezcla', 'DISEÑO MEZCLA', 'CONCRETO', 5, true, NOW()),
('co-flexion', 'FLEXION VIGA', 'CONCRETO', 6, true, NOW()),
('co-dens-cem', 'DENSIDAD CEMENTO', 'CONCRETO', 7, true, NOW()),
('co-graf-dis', 'GRAF. DISEÑO DE MEZCLA', 'CONCRETO', 8, true, NOW()),
('co-esclerometria', 'ESCLEROMETRIA', 'CONCRETO', 9, true, NOW()),

-- AGUA
('aq-sales', 'SALES', 'AGUA', 1, true, NOW()),
('aq-clorur', 'CLORUR', 'AGUA', 2, true, NOW()),
('aq-sulfa', 'SULFA', 'AGUA', 3, true, NOW()),
('aq-ph', 'PH', 'AGUA', 4, true, NOW()),
('aq-solidos', 'SÓLIDOS EN AGUA', 'AGUA', 5, true, NOW()),
('aq-mat-organica', 'MAT. ORGANICA', 'AGUA', 6, true, NOW()),

-- ALBAÑILERIA
('al-alabeo', 'ALABEO', 'ALBAÑILERIA', 1, true, NOW()),
('al-absorcion', 'ABSORCION', 'ALBAÑILERIA', 2, true, NOW()),
('al-eflorescencia', 'EFLORESCENCIA', 'ALBAÑILERIA', 3, true, NOW()),
('al-und-vacio', 'MEDIDA POR UND VACIO', 'ALBAÑILERIA', 4, true, NOW()),
('al-dis-mezcla', 'DISEÑO MEZCLA', 'ALBAÑILERIA', 5, true, NOW()),
('al-comp-ladrillo', 'COMPRESION LADRILLO', 'ALBAÑILERIA', 6, true, NOW()),
('al-comp-pilas', 'COMPRESION PILAS', 'ALBAÑILERIA', 7, true, NOW()),
('al-dimension', 'DIMENSIONAMIENTO', 'ALBAÑILERIA', 8, true, NOW()),
('al-tamaño', 'Medida de tamaño', 'ALBAÑILERIA', 9, true, NOW()),
('al-med-alabeo', 'MEDIDA DE ALABEO', 'ALBAÑILERIA', 10, true, NOW()),
('al-mod-rotura', 'MODULO DE ROTURA FLEXIÓN', 'ALBAÑILERIA', 11, true, NOW()),
('al-humedad', 'CONTENIDO DE HUMEDAD', 'ALBAÑILERIA', 12, true, NOW()),
('al-und-concreto', 'UNIDADES DE ALBAÑILERIA DE CONCRETO', 'ALBAÑILERIA', 13, true, NOW()),
('al-carga-rotura', 'CARGA ROTURA', 'ALBAÑILERIA', 14, true, NOW()),
('al-densidad', 'DENSIDAD', 'ALBAÑILERIA', 15, true, NOW()),

-- PAVIMENTO
('pa-riedel-weber', 'RIDEL WEBER', 'PAVIMENTO', 1, true, NOW()),
('pa-benkelman', 'VIGA BENKELMAN', 'PAVIMENTO', 2, true, NOW()),
('pa-espesor', 'ESPESOR PAV.', 'PAVIMENTO', 3, true, NOW()),
('pa-densidad', 'DENSIDAD PAV.', 'PAVIMENTO', 4, true, NOW()),
('pa-lavado-asf', 'LAVADO ASF.', 'PAVIMENTO', 5, true, NOW()),
('pa-marshall', 'MARSHALL', 'PAVIMENTO', 6, true, NOW()),
('pa-pendulo', 'PENDULO', 'PAVIMENTO', 7, true, NOW()),
('pa-extraccion', 'EXTRACCION PAV', 'PAVIMENTO', 8, true, NOW()),
('pa-iri', 'IRI', 'PAVIMENTO', 9, true, NOW()),
('pa-rice', 'PAV. RICE', 'PAVIMENTO', 10, true, NOW()),
('pa-trac-ind', 'TRACIÓN INDIRECTA', 'PAVIMENTO', 11, true, NOW()),
('pa-abson', 'ABSON', 'PAVIMENTO', 12, true, NOW()),
('pa-circ-arena', 'CIRCULO DE ARENA', 'PAVIMENTO', 13, true, NOW()),
('pa-lottman', 'LOTTMAN', 'PAVIMENTO', 14, true, NOW()),
('pa-imprimacion', 'IMPRIMACION', 'PAVIMENTO', 15, true, NOW())
ON CONFLICT (codigo) DO UPDATE SET
    nombre = EXCLUDED.nombre,
    area = EXCLUDED.area,
    orden = EXCLUDED.orden,
    activo = EXCLUDED.activo;
