-- Simplify role catalog: merge vendor into auxiliar_comercial and unify technician/lab roles.
BEGIN;

UPDATE perfiles SET role = 'auxiliar_comercial' WHERE role IN ('vendor', 'sig_el_rol');
UPDATE perfiles SET role = 'tecnico' WHERE role IN ('tecnico_general', 'tecnico_no_lab_write');
UPDATE perfiles SET role = 'laboratorio_lector' WHERE role = 'laboratorio_tipificador_no_lab_write';

UPDATE role_definitions
SET label = 'Técnico',
    description = 'Acceso técnico a ensayos sin clientes, proyectos, programación ni tablas de control',
    permissions = '{"tracing": {"read": true, "write": true, "delete": false}, "recepcion": {"read": true, "write": true, "delete": false}, "verificacion_muestras": {"read": true, "write": true, "delete": false}, "compresion": {"read": true, "write": true, "delete": false}, "humedad": {"read": true, "write": true, "delete": false}, "cont_humedad": {"read": true, "write": true, "delete": false}, "humedad_complete_demo": {"read": true, "write": true, "delete": false}, "planas": {"read": true, "write": true, "delete": false}, "caras": {"read": true, "write": true, "delete": false}, "cbr": {"read": true, "write": true, "delete": false}, "proctor": {"read": true, "write": true, "delete": false}, "llp": {"read": true, "write": true, "delete": false}, "gran_suelo": {"read": true, "write": true, "delete": false}, "gran_agregado": {"read": true, "write": true, "delete": false}, "cont_mat_organica": {"read": true, "write": true, "delete": false}, "terrones_fino_grueso": {"read": true, "write": true, "delete": false}, "azul_metileno": {"read": true, "write": true, "delete": false}, "part_livianas": {"read": true, "write": true, "delete": false}, "imp_organicas": {"read": true, "write": true, "delete": false}, "sul_magnesio": {"read": true, "write": true, "delete": false}, "angularidad": {"read": true, "write": true, "delete": false}, "abra": {"read": true, "write": true, "delete": false}, "abrass": {"read": true, "write": true, "delete": false}, "peso_unitario": {"read": true, "write": true, "delete": false}, "tamiz": {"read": true, "write": true, "delete": false}, "equi_arena": {"read": true, "write": true, "delete": false}, "ge_fino": {"read": true, "write": true, "delete": false}, "ge_grueso": {"read": true, "write": true, "delete": false}, "cd": {"read": true, "write": true, "delete": false}, "ph": {"read": true, "write": true, "delete": false}, "cloro_soluble": {"read": true, "write": true, "delete": false}, "sales_solubles": {"read": true, "write": true, "delete": false}, "sulfatos_solubles": {"read": true, "write": true, "delete": false}, "compresion_no_confinada": {"read": true, "write": true, "delete": false}, "configuracion": {"read": true, "write": false, "delete": false}}'::jsonb,
    updated_at = NOW()
WHERE role_id = 'tecnico';

UPDATE role_definitions
SET label = 'Laboratorio Tipificador',
    description = 'Acceso técnico a ensayos con tabla de control lab en edición',
    permissions = '{"tracing": {"read": true, "write": true, "delete": false}, "recepcion": {"read": true, "write": true, "delete": false}, "verificacion_muestras": {"read": true, "write": true, "delete": false}, "compresion": {"read": true, "write": true, "delete": false}, "humedad": {"read": true, "write": true, "delete": false}, "cont_humedad": {"read": true, "write": true, "delete": false}, "humedad_complete_demo": {"read": true, "write": true, "delete": false}, "planas": {"read": true, "write": true, "delete": false}, "caras": {"read": true, "write": true, "delete": false}, "cbr": {"read": true, "write": true, "delete": false}, "proctor": {"read": true, "write": true, "delete": false}, "llp": {"read": true, "write": true, "delete": false}, "gran_suelo": {"read": true, "write": true, "delete": false}, "gran_agregado": {"read": true, "write": true, "delete": false}, "cont_mat_organica": {"read": true, "write": true, "delete": false}, "terrones_fino_grueso": {"read": true, "write": true, "delete": false}, "azul_metileno": {"read": true, "write": true, "delete": false}, "part_livianas": {"read": true, "write": true, "delete": false}, "imp_organicas": {"read": true, "write": true, "delete": false}, "sul_magnesio": {"read": true, "write": true, "delete": false}, "angularidad": {"read": true, "write": true, "delete": false}, "abra": {"read": true, "write": true, "delete": false}, "abrass": {"read": true, "write": true, "delete": false}, "peso_unitario": {"read": true, "write": true, "delete": false}, "tamiz": {"read": true, "write": true, "delete": false}, "equi_arena": {"read": true, "write": true, "delete": false}, "ge_fino": {"read": true, "write": true, "delete": false}, "ge_grueso": {"read": true, "write": true, "delete": false}, "cd": {"read": true, "write": true, "delete": false}, "ph": {"read": true, "write": true, "delete": false}, "cloro_soluble": {"read": true, "write": true, "delete": false}, "sales_solubles": {"read": true, "write": true, "delete": false}, "sulfatos_solubles": {"read": true, "write": true, "delete": false}, "compresion_no_confinada": {"read": true, "write": true, "delete": false}, "configuracion": {"read": true, "write": false, "delete": false}, "laboratorio": {"read": true, "write": true, "delete": false}}'::jsonb,
    updated_at = NOW()
WHERE role_id = 'laboratorio_tipificador';

UPDATE role_definitions
SET label = 'Lector Laboratorio',
    description = 'Acceso técnico a ensayos con tabla de control lab en solo lectura',
    permissions = '{"tracing": {"read": true, "write": true, "delete": false}, "recepcion": {"read": true, "write": true, "delete": false}, "verificacion_muestras": {"read": true, "write": true, "delete": false}, "compresion": {"read": true, "write": true, "delete": false}, "humedad": {"read": true, "write": true, "delete": false}, "cont_humedad": {"read": true, "write": true, "delete": false}, "humedad_complete_demo": {"read": true, "write": true, "delete": false}, "planas": {"read": true, "write": true, "delete": false}, "caras": {"read": true, "write": true, "delete": false}, "cbr": {"read": true, "write": true, "delete": false}, "proctor": {"read": true, "write": true, "delete": false}, "llp": {"read": true, "write": true, "delete": false}, "gran_suelo": {"read": true, "write": true, "delete": false}, "gran_agregado": {"read": true, "write": true, "delete": false}, "cont_mat_organica": {"read": true, "write": true, "delete": false}, "terrones_fino_grueso": {"read": true, "write": true, "delete": false}, "azul_metileno": {"read": true, "write": true, "delete": false}, "part_livianas": {"read": true, "write": true, "delete": false}, "imp_organicas": {"read": true, "write": true, "delete": false}, "sul_magnesio": {"read": true, "write": true, "delete": false}, "angularidad": {"read": true, "write": true, "delete": false}, "abra": {"read": true, "write": true, "delete": false}, "abrass": {"read": true, "write": true, "delete": false}, "peso_unitario": {"read": true, "write": true, "delete": false}, "tamiz": {"read": true, "write": true, "delete": false}, "equi_arena": {"read": true, "write": true, "delete": false}, "ge_fino": {"read": true, "write": true, "delete": false}, "ge_grueso": {"read": true, "write": true, "delete": false}, "cd": {"read": true, "write": true, "delete": false}, "ph": {"read": true, "write": true, "delete": false}, "cloro_soluble": {"read": true, "write": true, "delete": false}, "sales_solubles": {"read": true, "write": true, "delete": false}, "sulfatos_solubles": {"read": true, "write": true, "delete": false}, "compresion_no_confinada": {"read": true, "write": true, "delete": false}, "configuracion": {"read": true, "write": false, "delete": false}, "laboratorio": {"read": true, "write": false, "delete": false}}'::jsonb,
    updated_at = NOW()
WHERE role_id = 'laboratorio_lector';

DELETE FROM role_definitions
WHERE role_id IN ('vendor', 'sig_el_rol', 'tecnico_general', 'tecnico_no_lab_write', 'laboratorio_tipificador_no_lab_write');

COMMIT;
